# Generated by Django 4.2.30 on 2026-06-08 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("escuelas", "0001_initial"),
        ("carreras", "0001_initial"),
        ("proceso", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ci", models.CharField(max_length=11, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("direccion", models.TextField(blank=True)),
                ("indice_10", models.PositiveIntegerField(blank=True, null=True)),
                ("indice_11", models.PositiveIntegerField(blank=True, null=True)),
                ("indice_12", models.PositiveIntegerField(blank=True, null=True)),
                ("indice_general", models.PositiveIntegerField(blank=True, null=True)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("tutor_nombre", models.CharField(blank=True, max_length=120)),
                ("tutor_correo", models.EmailField(blank=True, max_length=254)),
                ("tutor_telefono", models.CharField(blank=True, max_length=32)),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="escuelas.escuela",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estudiante",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
            },
        ),
        migrations.CreateModel(
            name="ResultadoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asignatura", models.CharField(max_length=128)),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_limite_reclamo", models.DateField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_examen",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_examen",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de Examen",
                "verbose_name_plural": "Resultados de Examen",
            },
        ),
        migrations.CreateModel(
            name="Reclamacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=16,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("respuesta", models.TextField(blank=True)),
                ("fecha_solicitud", models.DateField(blank=True, null=True)),
                ("fecha_respuesta", models.DateField(blank=True, null=True)),
                ("lugar_presentacion", models.CharField(blank=True, max_length=192)),
                ("fecha_presentacion", models.DateField(blank=True, null=True)),
                ("hora_presentacion", models.TimeField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamaciones",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamaciones",
                        to="estudiantes.resultadoexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reclamación",
                "verbose_name_plural": "Reclamaciones",
            },
        ),
        migrations.CreateModel(
            name="Otorgamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indice_otorgamiento", models.PositiveIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="otorgamientos",
                        to="carreras.carrera",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otorgamientos",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otorgamientos",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otorgamiento",
                "verbose_name_plural": "Otorgamientos",
            },
        ),
        migrations.CreateModel(
            name="ConfirmacionPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asignatura", models.CharField(max_length=128)),
                ("confirmo", models.BooleanField(blank=True, null=True)),
                ("fecha", models.DateField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmaciones_prueba",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmaciones_prueba",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Confirmación de Prueba",
                "verbose_name_plural": "Confirmaciones de Prueba",
            },
        ),
        migrations.CreateModel(
            name="BoletaSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("rechazado", "Rechazado"),
                            ("aprobado", "Aprobado"),
                        ],
                        default="borrador",
                        max_length=16,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "aprobada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_aprobadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boletas_solicitud",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boletas_solicitud",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleta de Solicitud",
                "verbose_name_plural": "Boletas de Solicitud",
            },
        ),
        migrations.CreateModel(
            name="BoletaInteres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enviada", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boletas_interes",
                        to="estudiantes.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boletas_interes",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Boleta de Interés",
                "verbose_name_plural": "Boletas de Interés",
            },
        ),
        migrations.CreateModel(
            name="SolicitudItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prioridad", models.PositiveSmallIntegerField()),
                (
                    "boleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="estudiantes.boletasolicitud",
                    ),
                ),
                (
                    "plan_plaza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carreras.planplaza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Solicitud",
                "verbose_name_plural": "Items de Solicitud",
                "unique_together": {("boleta", "prioridad")},
            },
        ),
        migrations.CreateModel(
            name="BoletaInteresItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prioridad", models.PositiveSmallIntegerField()),
                (
                    "boleta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="estudiantes.boletainteres",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="carreras.carrera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Boleta de Interés",
                "verbose_name_plural": "Items de Boleta de Interés",
                "unique_together": {("boleta", "prioridad")},
            },
        ),
    ]
