from django.urls import path

from .views import (
    ProvincialDashboardView,
    ProvincialEscuelaViewSet,
    ProvincialMunicipioViewSet,
    ProvincialProvinciaViewSet,
    ProvincialUserViewSet,
    ProvincialCarreraViewSet,
    ProvincialCesViewSet,
    ProvincialEtapaViewSet,
    ProvincialActivarEtapaView,
    ProvincialCerrarEtapaView,
    ProvincialProcesoViewSet,
    ProvincialReiniciarEtapasView,
    PublicEtapasDisponibilidadView,
    PublicPlanPlazaLandingView,
    PlanPlazaViewSet,
    CommissionSolicitudAuthorizationView,
)

urlpatterns = [
    path("dashboard/", ProvincialDashboardView.as_view(), name="provincial-dashboard"),
    path("municipios/", ProvincialMunicipioViewSet.as_view({"get": "list"}), name="provincial-municipios"),
    path("provincias/", ProvincialProvinciaViewSet.as_view({"get": "list"}), name="provincial-provincias"),
    path("escuelas/", ProvincialEscuelaViewSet.as_view({"get": "list", "post": "create"}), name="provincial-escuelas"),
    path("escuelas/<int:pk>/", ProvincialEscuelaViewSet.as_view({"get": "retrieve", "patch": "partial_update", "delete": "destroy"}), name="provincial-escuela-detail"),
    path("usuarios/", ProvincialUserViewSet.as_view({"get": "list", "post": "create"}), name="provincial-usuarios"),
    path("usuarios/<int:pk>/", ProvincialUserViewSet.as_view({"get": "retrieve", "patch": "partial_update", "delete": "destroy"}), name="provincial-usuario-detail"),
    path("carreras/", ProvincialCarreraViewSet.as_view({"get": "list", "post": "create"}), name="provincial-carreras"),
    path("carreras/<int:pk>/", ProvincialCarreraViewSet.as_view({"get": "retrieve", "patch": "partial_update", "delete": "destroy"}), name="provincial-carrera-detail"),
    path("ces/", ProvincialCesViewSet.as_view({"get": "list"}), name="provincial-ces"),
    path("etapas/", ProvincialEtapaViewSet.as_view({"get": "list"}), name="provincial-etapas"),
    path("etapas/disponibilidad/", PublicEtapasDisponibilidadView.as_view(), name="etapas-disponibilidad"),
    path("plan-plazas/landing/", PublicPlanPlazaLandingView.as_view(), name="plan-plazas-landing"),
    path("procesos/", ProvincialProcesoViewSet.as_view({"get": "list", "post": "create"}), name="provincial-procesos"),
    path("etapas/<int:pk>/activar/", ProvincialActivarEtapaView.as_view(), name="provincial-etapa-activar"),
    path("etapas/<int:pk>/cerrar/", ProvincialCerrarEtapaView.as_view(), name="provincial-etapa-cerrar"),
    path("etapas/reiniciar/", ProvincialReiniciarEtapasView.as_view(), name="provincial-etapas-reiniciar"),
    path("plan-plazas/", PlanPlazaViewSet.as_view({"get": "list", "post": "create"}), name="plan-plazas"),
    path("plan-plazas/<int:pk>/", PlanPlazaViewSet.as_view({"get": "retrieve", "patch": "partial_update", "delete": "destroy"}), name="plan-plaza-detail"),
    path("boletas-solicitud/<int:ballot_id>/autorizar-modificacion/", CommissionSolicitudAuthorizationView.as_view(), name="solicitud-authorize-modification"),
]