# Generated by Django 4.2.30 on 2026-08-21 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=200)),
                ("modulo", models.CharField(max_length=120)),
                (
                    "entidad",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrador"),
                            ("jefe_comision", "Jefe de Comisión de Ingreso"),
                            ("ingreso_provincial", "Repr. Ingreso Provincial"),
                            ("ingreso_municipal", "Repr. Ingreso Municipal"),
                            ("director_escuela", "Director de Escuela"),
                            ("secretario_escuela", "Secretaario de Escuela"),
                            ("estudiante", "Estudiante"),
                        ],
                        max_length=300,
                    ),
                ),
                ("datos_anteriores", models.CharField(max_length=500)),
                ("datos_nuevos", models.CharField(max_length=500)),
                ("ip", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
