from django.urls import path
from .views import (
    EscalafonEntryView, EscalafonListView, EscalafonSendView, EscalafonTemplateView,
    EscalafonReviewView, ProvincialEscalafonSummaryView, ProvincialEscalafonExportView,
    ExportCarrerasView, ExportCatalogView, ExportEscalafonView, ImportCarrerasView, ImportEscalafonView,
    ImportPlanPlazaView, ImportPlanPlazaExportView, PlanPlazaTemplateView,
    ImportOtorgamientoView, ImportCorteCarreraView, OtorgamientoSummaryView, ExportStageSixView, SchoolOtorgamientoListView, StudentEscalafonActionView, StudentInterestPdfExportView, StudentInterestExcelExportView, SolicitudPdfExportView, SolicitudExcelExportView,
    ImportTaskStatusView, ImportResultadosView, ResultadosListView, LandingResultadosView, LandingOtorgamientosView, LandingCortesView, LandingExcelExportView, ExportResultadosView, StudentResultClaimView, ResultClaimsListView, ResultClaimDecisionView,
)

urlpatterns = [
    path("tareas/<str:task_id>/", ImportTaskStatusView.as_view(), name="import-task-status"),
    path("import/plan-plaza/", ImportPlanPlazaView.as_view(), name="import-plan-plaza"),
    path("export/plan-plaza/", ImportPlanPlazaExportView.as_view(), name="export-plan-plaza"),
    path("export/plan-plaza/plantilla/", PlanPlazaTemplateView.as_view(), name="plan-plaza-template"),
    path("export/boleta-interes/", StudentInterestPdfExportView.as_view(), name="export-boleta-interes"),
    path("export/boleta-interes/excel/", StudentInterestExcelExportView.as_view(), name="export-boleta-interes-excel"),
    path("export/boleta-solicitud/", SolicitudPdfExportView.as_view(), name="export-boleta-solicitud"),
    path("export/boleta-solicitud/excel/", SolicitudExcelExportView.as_view(), name="export-boleta-solicitud-excel"),
    path("export/boleta-solicitud/<int:ballot_id>/", SolicitudPdfExportView.as_view(), name="export-school-boleta-solicitud"),
    path("export/boleta-solicitud/<int:ballot_id>/excel/", SolicitudExcelExportView.as_view(), name="export-school-boleta-solicitud-excel"),
    path("import/otorgamiento/", ImportOtorgamientoView.as_view(), name="import-otorgamiento"),
    path("import/cortes-carrera/", ImportCorteCarreraView.as_view(), name="import-cortes-carrera"),
    path("otorgamiento/resumen/", OtorgamientoSummaryView.as_view(), name="otorgamiento-summary"),
    path("otorgamiento/exportar/<str:kind>/", ExportStageSixView.as_view(), name="stage-six-export"),
    path("otorgamiento/escuela/", SchoolOtorgamientoListView.as_view(), name="school-otorgamiento-list"),
    path("import/carreras/", ImportCarrerasView.as_view(), name="import-carreras"),
    path("export/carreras/", ExportCarrerasView.as_view(), name="export-carreras"),
    path("export/provincias/", ExportCatalogView.as_view(resource_model="Provincia", filename="provincias.xlsx"), name="export-provincias"),
    path("export/municipios/", ExportCatalogView.as_view(resource_model="Municipio", filename="municipios.xlsx"), name="export-municipios"),
    path("export/escuelas/", ExportCatalogView.as_view(resource_model="Escuela", filename="escuelas.xlsx"), name="export-escuelas"),
    path("export/ces/", ExportCatalogView.as_view(resource_model="Ces", filename="ces.xlsx"), name="export-ces"),
    path("export/carreras-catalogo/", ExportCatalogView.as_view(resource_model="Carrera", filename="carreras.xlsx"), name="export-carreras-catalogo"),
    path("export/asignaturas/", ExportCatalogView.as_view(resource_model="Asignatura", filename="asignaturas.xlsx"), name="export-asignaturas"),
    path("export/tipos-otorgamiento/", ExportCatalogView.as_view(resource_model="TipoOtorgamiento", filename="tipos-otorgamiento.xlsx"), name="export-tipos-otorgamiento"),
    path("import/escalafon/", ImportEscalafonView.as_view(), name="import-escalafon"),
    path("import/resultados/", ImportResultadosView.as_view(), name="import-resultados"),
    path("resultados/", ResultadosListView.as_view(), name="resultados-list"),
    path("resultados/landing/", LandingResultadosView.as_view(), name="resultados-landing"),
    path("otorgamiento/landing/", LandingOtorgamientosView.as_view(), name="otorgamientos-landing"),
    path("cortes/landing/", LandingCortesView.as_view(), name="cortes-landing"),
    path("landing/export/<str:kind>/", LandingExcelExportView.as_view(), name="landing-excel-export"),
    path("resultados/<int:result_id>/reclamar/", StudentResultClaimView.as_view(), name="student-result-claim"),
    path("resultados/reclamaciones/", ResultClaimsListView.as_view(), name="result-claims-list"),
    path("resultados/reclamaciones/<int:claim_id>/", ResultClaimDecisionView.as_view(), name="result-claim-decision"),
    path("resultados/exportar/", ExportResultadosView.as_view(), name="resultados-exportar"),
    path("export/escalafon/", ExportEscalafonView.as_view(), name="export-escalafon"),
    path("escalafon/", EscalafonListView.as_view(), name="escalafon-list"),
    path("escalafon/resumen-provincial/", ProvincialEscalafonSummaryView.as_view(), name="escalafon-summary-provincial"),
    path("escalafon/exportar-provincial/", ProvincialEscalafonExportView.as_view(), name="escalafon-export-provincial"),
    path("escalafon/plantilla/", EscalafonTemplateView.as_view(), name="escalafon-template"),
    path("escalafon/<int:pk>/", EscalafonEntryView.as_view(), name="escalafon-entry"),
    path("escalafon/<int:pk>/revisar/", EscalafonReviewView.as_view(), name="escalafon-review"),
    path("escalafon/enviar-comision/", EscalafonSendView.as_view(), name="escalafon-send"),
    path("escalafon/mi-accion/<str:action>/", StudentEscalafonActionView.as_view(), name="student-escalafon-action"),
]
