# Generated by Django 4.2.30 on 2026-08-26 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0006_alter_estudiante_usuario_alter_estudiante_whatsapp"),
        ("superadmin", "0003_alter_identidadvisual_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escalafon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveIntegerField()),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalafones",
                        to="superadmin.escuela",
                    ),
                ),
            ],
            options={
                "ordering": ["-anio", "-fecha_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="EstudianteEscalafon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indice_10",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "indice_11",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "indice_12",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "indice_general",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "escalafon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estudiantes",
                        to="gestion_escuela.escalafon",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escalafones",
                        to="authentication.estudiante",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="estudianteescalafon",
            constraint=models.UniqueConstraint(
                fields=("escalafon", "estudiante"),
                name="unique_estudiante_en_escalafon",
            ),
        ),
        migrations.AddConstraint(
            model_name="escalafon",
            constraint=models.UniqueConstraint(
                fields=("escuela", "anio"), name="unique_escalafon_escuela_anio"
            ),
        ),
    ]
