# Generated by Django 4.2.30 on 2026-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_escuela", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudianteescalafon",
            name="aceptado",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="estudianteescalafon",
            name="causa_revision",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="estudianteescalafon",
            name="estado_revision",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("revisada", "Revisada")],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="estudianteescalafon",
            name="indices_bloqueados",
            field=models.BooleanField(default=False),
        ),
    ]
