# Generated by Django 4.2.30 on 2026-08-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_escuela", "0003_escalafon_proceso"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="escalafon",
            new_name="gestion_esc_proceso_9463b9_idx",
            old_name="gestion_esc_proceso_4a7c9d_idx",
        ),
    ]
