# Generated by Django 4.2.30 on 2026-08-27 15:24

from django.db import migrations, models


def migrate_status(apps, schema_editor):
    EscalafonItem = apps.get_model("gestion_escuela", "EscalafonItem")
    for item in EscalafonItem.objects.all().iterator():
        if item.aceptado is True:
            item.estado = "aceptado"
        elif item.estado_revision == "pendiente":
            item.estado = "por_revisar"
        else:
            item.estado = "sin_respuesta"
        item.save(update_fields=["estado"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_estudiante_tutor_telefono"),
        (
            "gestion_escuela",
            "0004_rename_gestion_esc_proceso_4a7c9d_idx_gestion_esc_proceso_9463b9_idx",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EstudianteEscalafon",
            new_name="EscalafonItem",
        ),
        migrations.AddField(
            model_name="escalafonitem",
            name="estado",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.RunPython(migrate_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="escalafonitem",
            name="estado",
            field=models.CharField(
                choices=[
                    ("aceptado", "Aceptado"),
                    ("sin_respuesta", "Sin respuesta"),
                    ("por_revisar", "Por revisar"),
                ],
                default="sin_respuesta",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="escalafonitem",
            constraint=models.UniqueConstraint(
                fields=("escalafon", "estudiante"),
                name="unique_estudiante_en_escalafon",
            ),
        ),
    ]
