# Generated by Django 4.2.30 on 2026-08-27 15:27

from django.db import migrations


def remove_legacy_columns(apps, schema_editor):
    table = "gestion_escuela_escalafonitem"
    columns = {
        row[1] for row in schema_editor.connection.cursor().execute(
            f'PRAGMA table_info("{table}")'
        )
    }
    model = apps.get_model("gestion_escuela", "EscalafonItem")
    for field_name in ("aceptado", "estado_revision"):
        if field_name in columns:
            schema_editor.remove_field(model, model._meta.get_field(field_name))


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_escuela", "0005_escalafonitem_delete_estudianteescalafon_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[migrations.RunPython(remove_legacy_columns, migrations.RunPython.noop)],
            state_operations=[
                migrations.RemoveField(model_name="escalafonitem", name="aceptado"),
                migrations.RemoveField(model_name="escalafonitem", name="estado_revision"),
            ],
        ),
    ]
