# Generated by Django 4.2.30 on 2026-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_escuela", "0006_remove_escalafonitem_aceptado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="escalafon",
            name="estado",
            field=models.CharField(
                choices=[("por_enviar", "Por enviar"), ("enviado", "Enviado")],
                default="por_enviar",
                max_length=20,
            ),
        ),
    ]
