# Generated by Django 4.2.30 on 2026-07-07 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0002_asignatura_carrera_ces_escuela_identidadvisual_and_more"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ci", models.CharField(max_length=11, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("apellidos", models.CharField(max_length=200)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino")], max_length=1
                    ),
                ),
                ("direccion", models.CharField(max_length=500)),
                (
                    "whatsapp",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="CU"
                    ),
                ),
                ("indice_10", models.FloatField()),
                ("indice_11", models.FloatField()),
                ("indice_12", models.FloatField()),
                ("indice_general", models.FloatField()),
                (
                    "tutor_nombre",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "tutor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "escuela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudiantes",
                        to="superadmin.escuela",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="activo",
        ),
        migrations.AddField(
            model_name="usuario",
            name="escuela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="superadmin.escuela",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="superadmin.municipio",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="usuarios",
                to="superadmin.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="rolpermiso",
            name="permiso",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="rolpermiso",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("jefe_comision", "Jefe de Comisión de Ingreso"),
                    ("ingreso_provincial", "Repr. Ingreso Provincial"),
                    ("ingreso_municipal", "Repr. Ingreso Municipal"),
                    ("director_escuela", "Director de Escuela"),
                    ("secretario_escuela", "Secretaario de Escuela"),
                    ("estudiante", "Estudiante"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("jefe_comision", "Jefe de Comisión de Ingreso"),
                    ("ingreso_provincial", "Repr. Ingreso Provincial"),
                    ("ingreso_municipal", "Repr. Ingreso Municipal"),
                    ("director_escuela", "Director de Escuela"),
                    ("secretario_escuela", "Secretaario de Escuela"),
                    ("estudiante", "Estudiante"),
                ],
                default="estudiante",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name="Rol",
        ),
        migrations.AddField(
            model_name="estudiante",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estudiante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
