# Generated by Django 4.2.30 on 2026-08-25 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_usuario_role_scope_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usuario",
            options={},
        ),
    ]
