# Generated by Django 4.2.30 on 2026-08-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_usuario_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolpermiso",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("jefe_comision", "Jefe de Comisión de Ingreso"),
                    ("ingreso_provincial", "Repr. Ingreso Provincial"),
                    ("ingreso_municipal", "Repr. Ingreso Municipal"),
                    ("director_escuela", "Director de Escuela"),
                    ("secretario_escuela", "Secretario de Escuela"),
                    ("estudiante", "Estudiante"),
                ],
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Super Administrador"),
                    ("jefe_comision", "Jefe de Comisión de Ingreso"),
                    ("ingreso_provincial", "Repr. Ingreso Provincial"),
                    ("ingreso_municipal", "Repr. Ingreso Municipal"),
                    ("director_escuela", "Director de Escuela"),
                    ("secretario_escuela", "Secretario de Escuela"),
                    ("estudiante", "Estudiante"),
                ],
                default="estudiante",
                max_length=150,
            ),
        ),
    ]
