# Generated by Django 4.2.30 on 2026-08-26 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_rolpermiso_rol_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="estudiante",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="whatsapp",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region="CU"
            ),
        ),
    ]
