# Generated by Django 4.2.30 on 2026-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_estudiante_usuario_alter_estudiante_whatsapp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estudiante",
            name="indice_10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="indice_11",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="indice_12",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="indice_general",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
