# Generated by Django 4.2.30 on 2026-08-27 14:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_estudiante_indice_10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="tutor_telefono",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="CU"
            ),
        ),
    ]
