# Generated by Django 4.2.30 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_loginattempt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="politica_privacidad_aceptada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuario",
            name="politica_privacidad_fecha_aceptacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="politica_privacidad_version",
            field=models.CharField(default="2025.1", max_length=20),
        ),
    ]
