# Generated by Django 4.2.30 on 2026-09-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_usuario_politica_privacidad_aceptada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="debe_cambiar_password",
            field=models.BooleanField(
                default=False,
                help_text="La contraseña la fijó un administrador: debe cambiarla en el primer inicio de sesión.",
            ),
        ),
    ]
