# Generated by Django 4.2.30 on 2026-07-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("superadmin", "0002_asignatura_carrera_ces_escuela_identidadvisual_and_more"),
        (
            "authentication",
            "0002_estudiante_remove_usuario_activo_usuario_escuela_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Proceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.DateField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                (
                    "etapa",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Publicación y validación del escalafón."),
                            ("2", "Llenado de boleta de interés."),
                            ("3", "Plan de plazas y boleta de solicitud."),
                            ("4", "Confirmación de las pruebas de ingreso."),
                            (
                                "5",
                                "Publicación de resultados en las pruebas de ingreso..",
                            ),
                            ("6", "Otorgamiento de carreras."),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("config_consulta_nota_publica", models.BooleanField(default=False)),
                ("config_consulta_otorg_publico", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PlanPlaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_plazas", models.PositiveIntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("A", "Ambos"), ("F", "Femenino"), ("M", "Masculino")],
                        max_length=1,
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plaza",
                        to="superadmin.carrera",
                    ),
                ),
                (
                    "ces",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plaza",
                        to="superadmin.ces",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plaza",
                        to="gestion_provincial.proceso",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plaza",
                        to="superadmin.provincia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Otorgamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indice_otorgamiento", models.FloatField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="otorgamiento",
                        to="superadmin.carrera",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otorgamiento",
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="otorgamiento",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CorteCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indice_corte", models.FloatField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corte_carrera",
                        to="superadmin.carrera",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corte_carrera",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
    ]
