# Generated by Django 4.2.30 on 2026-08-24 13:52

from django.db import migrations, models
import django.db.models.deletion


ETAPAS_NOMBRES = {
    1: "Publicación y validación del escalafón.",
    2: "Llenado de boleta de interés.",
    3: "Plan de plazas y boleta de solicitud.",
    4: "Confirmación de las pruebas de ingreso.",
    5: "Publicación de resultados en las pruebas de ingreso.",
    6: "Otorgamiento de carreras.",
}


def crear_etapas_existentes(apps, schema_editor):
    Proceso = apps.get_model("gestion_provincial", "Proceso")
    Etapa = apps.get_model("gestion_provincial", "Etapa")
    Etapa.objects.bulk_create(
        Etapa(proceso=proceso, numero=numero, nombre=nombre)
        for proceso in Proceso.objects.all()
        for numero, nombre in ETAPAS_NOMBRES.items()
    )


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_provincial", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proceso",
            name="etapa",
        ),
        migrations.CreateModel(
            name="Etapa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("nombre", models.CharField(max_length=150)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
            options={
                "ordering": ["numero"],
            },
        ),
        migrations.AddConstraint(
            model_name="etapa",
            constraint=models.UniqueConstraint(
                fields=("proceso", "numero"), name="unique_etapa_por_proceso"
            ),
        ),
        migrations.RunPython(crear_etapas_existentes, migrations.RunPython.noop),
    ]
