# Generated by Django 4.2.30 on 2026-08-24 14:18

from django.db import migrations, models
import django.db.models.deletion


ETAPAS_NOMBRES = {
    1: "Publicación y validación del escalafón.",
    2: "Llenado de boleta de interés.",
    3: "Plan de plazas y boleta de solicitud.",
    4: "Confirmación de las pruebas de ingreso.",
    5: "Publicación de resultados en las pruebas de ingreso.",
    6: "Otorgamiento de carreras.",
}


def preparar_catalogo_y_procesos(apps, schema_editor):
    Proceso = apps.get_model("gestion_provincial", "Proceso")
    Etapa = apps.get_model("gestion_provincial", "Etapa")
    catalogo = {}
    for numero, nombre in ETAPAS_NOMBRES.items():
        etapas = list(Etapa.objects.filter(numero=numero).order_by("-proceso_id"))
        if not etapas:
            continue
        etapa = etapas[0]
        etapa.nombre = nombre
        etapa.save(update_fields=["nombre"])
        etapa_ids = [item.id for item in etapas[1:]]
        Etapa.objects.filter(id__in=etapa_ids).delete()
        catalogo[numero] = etapa

    for proceso in Proceso.objects.all():
        activa = next(
            (item for item in catalogo.values() if item.proceso_id == proceso.id),
            catalogo.get(max(catalogo, default=1)),
        )
        if activa:
            proceso.etapa_id = activa.id
            proceso.save(update_fields=["etapa"])


def completar_catalogo(apps, schema_editor):
    Etapa = apps.get_model("gestion_provincial", "Etapa")
    for nombre in ETAPAS_NOMBRES.values():
        Etapa.objects.get_or_create(nombre=nombre)


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_provincial", "0002_remove_proceso_etapa_etapa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proceso",
            name="etapa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos",
                to="gestion_provincial.etapa",
            ),
        ),
        migrations.RunPython(preparar_catalogo_y_procesos, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name="etapa",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveConstraint(
            model_name="etapa",
            name="unique_etapa_por_proceso",
        ),
        migrations.RemoveField(
            model_name="etapa",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="etapa",
            name="proceso",
        ),
        migrations.RemoveField(
            model_name="proceso",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="proceso",
            name="fecha_inicio",
        ),
        migrations.AlterField(
            model_name="etapa",
            name="nombre",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RunPython(completar_catalogo, migrations.RunPython.noop),
    ]
