# Generated by Django 4.2.30 on 2026-08-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_provincial", "0003_alter_etapa_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etapa",
            name="nombre",
            field=models.CharField(
                choices=[
                    (
                        "Publicación y validación del escalafón.",
                        "Publicación y validación del escalafón.",
                    ),
                    ("Llenado de boleta de interés.", "Llenado de boleta de interés."),
                    (
                        "Plan de plazas y boleta de solicitud.",
                        "Plan de plazas y boleta de solicitud.",
                    ),
                    (
                        "Confirmación de las pruebas de ingreso.",
                        "Confirmación de las pruebas de ingreso.",
                    ),
                    (
                        "Publicación de resultados en las pruebas de ingreso.",
                        "Publicación de resultados en las pruebas de ingreso.",
                    ),
                    ("Otorgamiento de carreras.", "Otorgamiento de carreras."),
                ],
                max_length=150,
                unique=True,
            ),
        ),
    ]
