# Generated by Django 4.2.30 on 2026-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_provincial", "0004_alter_etapa_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapa",
            name="estado",
            field=models.CharField(
                choices=[
                    ("no_iniciada", "No iniciada"),
                    ("en_curso", "En curso"),
                    ("completada", "Completada"),
                ],
                default="no_iniciada",
                max_length=20,
            ),
        ),
    ]
