# Generated by Django 4.2.30 on 2026-08-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_provincial", "0006_planplaza_otorgamiento_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planplazaitem",
            name="carrera",
        ),
        migrations.RemoveField(
            model_name="planplazaitem",
            name="ces",
        ),
        migrations.RemoveField(
            model_name="planplazaitem",
            name="plan_plaza",
        ),
        migrations.RemoveField(
            model_name="planplazaitem",
            name="provincia",
        ),
        migrations.AlterField(
            model_name="planplaza",
            name="otorgamiento_tipo",
            field=models.CharField(
                choices=[("municipal", "Municipal"), ("provincial", "Provincial")],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="proceso",
            name="etapa",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="procesos",
                to="gestion_provincial.etapa",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="proceso",
            constraint=models.UniqueConstraint(
                fields=("anio", "etapa"), name="unique_proceso_anio_etapa"
            ),
        ),
        migrations.DeleteModel(
            name="PlanPlazaItem",
        ),
    ]
