# Generated by Django 4.2.30 on 2026-06-08 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nomencladores", "__first__"),
        ("proceso", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=64, unique=True)),
                ("nombre", models.CharField(max_length=192)),
                ("activa", models.BooleanField(default=True)),
                (
                    "ces",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carreras",
                        to="nomencladores.ces",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carreras",
                        to="nomencladores.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
            },
        ),
        migrations.CreateModel(
            name="PlanPlaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_plazas", models.PositiveIntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("A", "Ambos")],
                        default="A",
                        max_length=1,
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plazas",
                        to="carreras.carrera",
                    ),
                ),
                (
                    "ces",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plazas_ces",
                        to="nomencladores.ces",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_plazas",
                        to="proceso.proceso",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plazas_provincia",
                        to="nomencladores.provincia",
                    ),
                ),
                (
                    "tipo_otorgamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_plazas",
                        to="nomencladores.otorgamientotipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan de Plaza",
                "verbose_name_plural": "Planes de Plazas",
                "unique_together": {
                    ("proceso", "carrera", "tipo_otorgamiento", "sexo")
                },
            },
        ),
        migrations.CreateModel(
            name="CorteCarrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indice_corte", models.PositiveIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cortes",
                        to="carreras.carrera",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cortes_carrera",
                        to="proceso.proceso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corte de Carrera",
                "verbose_name_plural": "Cortes de Carrera",
                "unique_together": {("proceso", "carrera")},
            },
        ),
    ]
