# Generated by Django 4.2.30 on 2026-07-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("superadmin", "0002_asignatura_carrera_ces_escuela_identidadvisual_and_more"),
        (
            "authentication",
            "0002_estudiante_remove_usuario_activo_usuario_escuela_and_more",
        ),
        ("gestion_provincial", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoletaInteres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enviada", models.BooleanField(default=False)),
                ("fecha_enviada", models.DateField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_interes",
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boleta_interes",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoletaSolicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("por_enviar", "Por enviar"),
                            ("por_aprobar", "Por aprobar"),
                            ("aprobada", "Aprobada"),
                        ],
                        default="por_enviar",
                        max_length=100,
                    ),
                ),
                ("fecha_enviada", models.DateField(blank=True, null=True)),
                (
                    "aprobada_por",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("fecha_aprobada", models.DateField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_solicitud",
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boleta_solicitud",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultadoExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nota", models.FloatField()),
                ("fecha_limite_reclamo", models.DateField()),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="superadmin.asignatura",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado_examen",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reclamacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=500)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=100,
                    ),
                ),
                ("fecha_solicitud", models.DateField(auto_now_add=True)),
                ("fecha_respuesta", models.DateField(blank=True, null=True)),
                (
                    "lugar_presentacion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("fecha_presentacion", models.DateTimeField(blank=True, null=True)),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "resultado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamacion",
                        to="gestion_personal.resultadoexamen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfirmacionPrueba",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmada", models.BooleanField(blank=True, null=True)),
                ("fecha_prueba", models.DateTimeField()),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="superadmin.asignatura",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.estudiante",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="confirmacion_prueba",
                        to="gestion_provincial.proceso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoletaSolicitudItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prioridad", models.PositiveSmallIntegerField()),
                (
                    "boleta_solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_solicitud",
                        to="gestion_personal.boletasolicitud",
                    ),
                ),
                (
                    "plan_plaza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_solicitud",
                        to="gestion_provincial.planplaza",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoletaInteresItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prioridad", models.PositiveSmallIntegerField()),
                (
                    "boleta_interes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_interes",
                        to="gestion_personal.boletainteres",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boleta_interes",
                        to="superadmin.carrera",
                    ),
                ),
            ],
        ),
    ]
