# Generated by Django 4.2.30 on 2026-08-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_personal", "0004_boletasolicitud_modificada"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletasolicitud",
            name="comentario_respuesta",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="boletasolicitud",
            name="motivo_modificacion",
            field=models.TextField(blank=True, default=""),
        ),
    ]
