# Generated by Django 4.2.30 on 2026-08-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_personal", "0005_boletasolicitud_comentario_respuesta_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="boletasolicitud",
            name="comentario_respuesta",
        ),
        migrations.RemoveField(
            model_name="boletasolicitud",
            name="modificada",
        ),
        migrations.RemoveField(
            model_name="boletasolicitud",
            name="motivo_modificacion",
        ),
        migrations.AlterField(
            model_name="boletasolicitud",
            name="estado",
            field=models.CharField(
                choices=[
                    ("por_enviar", "Por enviar"),
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("modificada", "Modificada"),
                ],
                default="por_enviar",
                max_length=100,
            ),
        ),
    ]
