# Generated by Django 4.2.30 on 2026-08-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_personal", "0007_boletasolicituditemanterior"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confirmacionprueba",
            name="confirmada",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
