# Generated by Django 4.2.30 on 2026-08-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_personal", "0008_alter_confirmacionprueba_confirmada"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="confirmacionprueba",
            constraint=models.UniqueConstraint(
                fields=("estudiante", "proceso", "asignatura"),
                name="unique_confirmacion_estudiante_proceso_asignatura",
            ),
        ),
    ]
