# Generated by Django 4.2.30 on 2026-06-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AsignaturaExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("codigo", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "verbose_name": "Asignatura de Examen",
                "verbose_name_plural": "Asignaturas de Examen",
            },
        ),
        migrations.CreateModel(
            name="Ces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=192)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Centro de Educación Superior",
                "verbose_name_plural": "Centros de Educación Superior",
            },
        ),
        migrations.CreateModel(
            name="OtorgamientoTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Tipo de Otorgamiento",
                "verbose_name_plural": "Tipos de Otorgamiento",
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128, unique=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("activo", models.BooleanField(default=True)),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipios",
                        to="nomencladores.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
                "unique_together": {("nombre", "provincia")},
            },
        ),
    ]
