# Generated by Django 4.2.30 on 2026-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuperAdminConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL del logo institucional"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#0ea5e9",
                        help_text="Color principal de la interfaz",
                        max_length=32,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#0284c7", help_text="Color secundario", max_length=32
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#14b8a6",
                        help_text="Color de acento para botones y alertas",
                        max_length=32,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Global Super Administrador",
                "verbose_name_plural": "Configuraciones Globales Super Administrador",
            },
        ),
    ]
