# Generated by Django 4.2.30 on 2026-07-07 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=150, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Centro de Educación Superior",
                "verbose_name_plural": "Centros de Educación Superior",
            },
        ),
        migrations.CreateModel(
            name="Escuela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=300)),
                ("codigo", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Preuniversitario",
                "verbose_name_plural": "Preuniversitarios",
            },
        ),
        migrations.CreateModel(
            name="IdentidadVisual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL del logo institucional"),
                ),
                (
                    "nombre_sistema",
                    models.CharField(default="IngresoSUP", max_length=100),
                ),
                ("tipografia", models.CharField(default="Segoe UI", max_length=100)),
                (
                    "color_primario",
                    models.CharField(
                        default="#1F4E79",
                        help_text="Color principal de la interfaz",
                        max_length=32,
                    ),
                ),
                (
                    "color_secundario",
                    models.CharField(
                        default="#2E75B6", help_text="Color secundario", max_length=32
                    ),
                ),
                (
                    "color_acento",
                    models.CharField(
                        default="#5BA3D9",
                        help_text="Color de acento para botones y alertas",
                        max_length=32,
                    ),
                ),
                (
                    "color_fondo",
                    models.CharField(
                        default="#D6E4F0", help_text="Color de fondo", max_length=32
                    ),
                ),
                (
                    "color_exito",
                    models.CharField(
                        default="#1A7A4A",
                        help_text="Color de acciones exitosas",
                        max_length=32,
                    ),
                ),
                (
                    "color_error",
                    models.CharField(
                        default="#C0392B",
                        help_text="Color de acciones de error",
                        max_length=32,
                    ),
                ),
                ("fecha_creado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración Global Super Administrador",
                "verbose_name_plural": "Configuraciones Globales Super Administrador",
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=128)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("activa", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SuperAdminConfig",
        ),
        migrations.AddField(
            model_name="municipio",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="municipios",
                to="superadmin.provincia",
            ),
        ),
        migrations.AddField(
            model_name="escuela",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escuelas",
                to="superadmin.municipio",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="ces",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carreras",
                to="superadmin.ces",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carreras",
                to="superadmin.provincia",
            ),
        ),
    ]
