# Generated by Django 4.2.30 on 2026-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0004_seed_additional_careers"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOtorgamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Otorgamiento",
                "verbose_name_plural": "Tipos de Otorgamiento",
            },
        ),
    ]
