# Generated by Django 4.2.30 on 2026-09-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0006_seed_tipos_otorgamiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="asignatura",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asignatura",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="carrera",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="carrera",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="ces",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ces",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="escuela",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="municipio",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="municipio",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="provincia",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="provincia",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tipootorgamiento",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tipootorgamiento",
            name="fecha_ultima_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
