# Generated by Django 4.2.30 on 2026-09-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("superadmin", "0007_asignatura_descripcion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ces",
            name="sede_principal",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="ces",
            name="sitio_web",
            field=models.URLField(blank=True, default="", max_length=300),
        ),
    ]
