# Generated by Django 4.2.30 on 2026-06-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nomencladores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anio", models.PositiveSmallIntegerField()),
                (
                    "etapa_activa",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "Etapa 1"),
                            (2, "Etapa 2"),
                            (3, "Etapa 3"),
                            (4, "Etapa 4"),
                            (5, "Etapa 5"),
                            (6, "Etapa 6"),
                        ],
                        null=True,
                    ),
                ),
                ("config_consulta_nota_publica", models.BooleanField(default=False)),
                ("config_consulta_otorg_publica", models.BooleanField(default=False)),
                ("fechas_etapas", models.JSONField(blank=True, default=dict)),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="procesos",
                        to="nomencladores.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso",
                "verbose_name_plural": "Procesos",
                "unique_together": {("anio", "provincia")},
            },
        ),
    ]
